steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/seniormind-frontend', '--build-arg', 'REACT_APP_API_BASE_URL=$_REACT_APP_API_BASE_URL', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/seniormind-frontend']
